version: '2'
services:
  eos-fuzz:
    container_name: eos-fuzz
    image: eos-fuzz:afl
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
    - ./results:/results
    logging:
      driver: none

  eos:
    container_name: eos
    image: eos-fuzz:default
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
    - ./results:/results
    logging:
      driver: none
